import "../styles/globals.css";
import { getServerSession } from "next-auth";
import Login from "../components/Login";
import SessionProvider from "../components/SessionProvider";
import ToastProvider from "../components/ToastProvider";
import { authOptions } from "../pages/api/auth/[...nextauth]";
import Topbar from "../components/Topbar";
import UserContextProvider from "../components/UserContextProvider";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <UserContextProvider>
          <SessionProvider session={session}>
              {
              (session)
              ?
              <div>
                <Topbar/>
                {children}
                <ToastProvider/>
              </div>
              :
                <Login />
              }
          </SessionProvider>
        </UserContextProvider>
      </body>
    </html>
  )
}
