import "../styles/globals.css";
import { getServerSession } from "next-auth";
import Login from "../components/Login";
import SessionProvider from "../components/SessionProvider";
import ToastProvider from "../components/ToastProvider";
import { authOptions } from "../pages/api/auth/[...nextauth]";
import Topbar from "../components/Topbar";
import UserContextProvider from "../components/UserContextProvider";
import ParkContextProvider from "../components/ParkContextProvider";

export const metadata = {
  title: 'ParkPilot',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <UserContextProvider>
          <ParkContextProvider>
            <SessionProvider session={session}>
                {
                (session)
                ?
                <div>
                  <Topbar/>
                  {children}
                  <ToastProvider/>
                </div>
                :
                  <Login />
                }
            </SessionProvider>
          </ParkContextProvider>
        </UserContextProvider>
      </body>
    </html>
  )
}
